dist:     trusty
sudo:     false
language: go

go:
  - 1.9
go_import_path: github.com/dmacvicar/terraform-provider-libvirt
install:        true
before_script:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
apt:
  packages:
    - libvirt-dev
script:
  - make gofmtcheck
  - make vet
  - golint -set_exit_status libvirt/
  - make test
  - goveralls -coverprofile=profile.cov -service=travis-ci
