dist: trusty
language: go

go:
  - 1.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget
  - sudo apt-get build-dep -y libvirt
  - wget https://libvirt.org/sources/libvirt-1.2.14.tar.gz
  - sudo mkdir -p /usr/src
  - sudo tar xvzf libvirt-1.2.14.tar.gz -C /usr/src
  - pushd /usr/src/libvirt-1.2.14
  - sudo ./configure --prefix=/usr/
  - sudo make
  - sudo make install
  - sudo libvirtd -d
  - popd
  - go get -u github.com/govend/govend
  - govend -v

install:
  - go build .

# override the custom test script, this would trigger
# also the execution of the unit tests of the vendored
# code
script:
  - go test ./libvirt
