dist: trusty
language: go

go:
  - 1.9
go_import_path: github.com/dmacvicar/terraform-provider-libvirt
install: true
before_script:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - sudo bash ./travis/setup-host
  - sudo lxc exec libvirt -- bash /code/travis/setup-guest
script:
  - bash ./travis/gofmtcheck.sh
# FIXME: enable this when all golint issue are fixed
# - golint -set_exit_status libvirt/
  - sudo lxc exec libvirt -- bash /code/travis/run-tests-inside-guest
  - sudo lxc file pull libvirt/root/go/src/github.com/dmacvicar/terraform-provider-libvirt/profile.cov .
  - goveralls -coverprofile=profile.cov -service=travis-ci
